In [1]:
import os
import pandas as pd

In [2]:
DATA_KIND = "time"
DATA_PATH = "/Volumes/Samsung_T3/SKT_1/"+DATA_KIND

In [3]:
# 한글폰트 추가하기
import matplotlib.font_manager as fm
path = '/Library/Fonts/NanumPen.ttf'
fontprop = fm.FontProperties(fname=path, size=30)

In [4]:
from os import listdir
from os.path import isfile, join

In [5]:
# 전처리하기 여기서는 "|" 를  "," 로 바꿔준다
def make_csv_format(csv_raw_path=DATA_PATH, csv_raw_name=None):
    if not os.path.exists(csv_raw_path+'/new'):
        os.makedirs(csv_raw_path+'/new')
    
    new_csv = open(csv_raw_path+'/new/'+ 'new_' + csv_raw_name,'w')
    with open(csv_raw_path+'/'+csv_raw_name,'r') as filelist:
        for afile in filelist:
            #afile = (afile.rstrip('\n')).replace('|',',')
            afile = afile.replace('|',',')
            new_csv.write(afile)
            #print(afile)
    new_csv.close()

In [6]:
onlyfiles = [f for f in listdir(DATA_PATH) if isfile(join(DATA_PATH, f))]

In [7]:
for acsv in onlyfiles:
    if acsv.endswith('.CSV'):
        print (acsv)
        make_csv_format(csv_raw_name=acsv)

FLOW_TIME_201701.CSV
FLOW_TIME_201702.CSV
FLOW_TIME_201703.CSV
FLOW_TIME_201704.CSV
FLOW_TIME_201705.CSV
FLOW_TIME_201706.CSV
FLOW_TIME_201707.CSV
FLOW_TIME_201708.CSV
FLOW_TIME_201709.CSV
FLOW_TIME_201710.CSV
FLOW_TIME_201711.CSV
FLOW_TIME_201712.CSV
FLOW_TIME_201801.CSV
FLOW_TIME_201802.CSV
FLOW_TIME_201803.CSV
FLOW_TIME_201804.CSV
FLOW_TIME_201805.CSV
FLOW_TIME_201806.CSV
FLOW_TIME_201807.CSV
FLOW_TIME_201808.CSV
FLOW_TIME_201809.CSV
FLOW_TIME_201810.CSV
FLOW_TIME_201811.CSV
FLOW_TIME_201812.CSV

In [8]:
#
DATA_PATH = "/Volumes/Samsung_T3/SKT_1/"+DATA_KIND
DATA_PATH += "/new"

def load_data(csv_path=DATA_PATH, csv_name=None):
    csv_path = os.path.join(csv_path, csv_name)
    print(csv_path)
    return pd.read_csv(csv_path)

In [9]:
onlyfiles = [f for f in listdir(DATA_PATH) if isfile(join(DATA_PATH, f))]

In [10]:
onlyfiles

['new_FLOW_TIME_201701.CSV',
 'new_FLOW_TIME_201702.CSV',
 'new_FLOW_TIME_201703.CSV',
 'new_FLOW_TIME_201704.CSV',
 'new_FLOW_TIME_201705.CSV',
 'new_FLOW_TIME_201706.CSV',
 'new_FLOW_TIME_201707.CSV',
 'new_FLOW_TIME_201708.CSV',
 'new_FLOW_TIME_201709.CSV',
 'new_FLOW_TIME_201710.CSV',
 'new_FLOW_TIME_201711.CSV',
 'new_FLOW_TIME_201712.CSV',
 'new_FLOW_TIME_201801.CSV',
 'new_FLOW_TIME_201802.CSV',
 'new_FLOW_TIME_201803.CSV',
 'new_FLOW_TIME_201804.CSV',
 'new_FLOW_TIME_201805.CSV',
 'new_FLOW_TIME_201806.CSV',
 'new_FLOW_TIME_201807.CSV',
 'new_FLOW_TIME_201808.CSV',
 'new_FLOW_TIME_201809.CSV',
 'new_FLOW_TIME_201810.CSV',
 'new_FLOW_TIME_201811.CSV',
 'new_FLOW_TIME_201812.CSV']

In [11]:
total_data = load_data(csv_name='new_FLOW_TIME_201702.CSV')

for acsv in onlyfiles[1:]:
    #print(acsv)
    total_data.append(load_data(csv_name=acsv))

/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201702.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201702.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201703.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201704.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201705.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201706.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201707.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201708.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201709.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201710.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201711.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201712.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201801.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201802.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201803.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201804.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201805.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201806.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201807.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201808.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201809.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201810.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201811.CSV
/Volumes/Samsung_T3/SKT_1/time/new/new_FLOW_TIME_201812.CSV

In [12]:
total_data.tail()

,STD_YM,BLOCK_CD,X_COORD,Y_COORD,TMST_00,TMST_01,TMST_02,TMST_03,TMST_04,TMST_05,...,TMST_14,TMST_15,TMST_16,TMST_17,TMST_18,TMST_19,TMST_20,TMST_21,TMST_22,TMST_23
94434,201702,34011370100010000001,992783.991787,1.862629e+06,0.20,0.17,0.06,0.15,0.05,0.09,...,0.73,0.66,0.62,0.53,0.48,0.32,0.26,0.25,0.15,0.12
94435,201702,34011370100010000001,992833.991787,1.862229e+06,0.14,0.12,0.03,0.09,0.03,0.06,...,0.48,0.43,0.41,0.34,0.32,0.20,0.17,0.16,0.09,0.08
94436,201702,34011370100010000001,992833.991787,1.862479e+06,0.23,0.22,0.22,0.23,0.17,0.41,...,1.55,1.56,1.41,1.28,0.94,0.65,0.86,0.43,0.23,0.23
94437,201702,34011370100010000001,992833.991787,1.862579e+06,0.32,0.29,0.08,0.24,0.08,0.16,...,1.20,1.10,1.03,0.87,0.79,0.53,0.43,0.41,0.24,0.20
94438,201702,34011370100010000001,992883.991787,1.862529e+06,0.34,0.33,0.31,0.33,0.26,0.60,...,2.30,2.31,2.07,1.87,1.38,0.96,1.27,0.65,0.35,0.34

In [13]:

# Common imports
import numpy as np
import os

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", DATA_KIND)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension) # TODO 저장할 디렉토리를 새로 만들어야 하는 경우 다루어주기
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [ ]:
import matplotlib.pyplot as plt
total_data.hist(bins=50, figsize=(20,15))
save_fig("attribute_histogram_plots")
plt.show()

In [15]:
# 총 유동인구 수 컬럼 만들기
time_name = ["TMST_00","TMST_01","TMST_02","TMST_03", "TMST_04", "TMST_05", "TMST_06", "TMST_07", "TMST_08",
            "TMST_09", "TMST_10", "TMST_11", "TMST_12", "TMST_13", "TMST_14", "TMST_15", "TMST_16", "TMST_17",
            "TMST_18", "TMST_19", "TMST_20", "TMST_21", "TMST_22", "TMST_23"]

total_data["total_population"] = total_data["TMST_00"]
for t_name in time_name[1:]:
    total_data["total_population"] = total_data["total_population"]+total_data[t_name]

In [16]:
for t_name in time_name:
    total_data[t_name+"_population_ratio"] = total_data[t_name]/ total_data["total_population"]

In [17]:
import geopandas as gpd
import descartes

SHAPE_DIR = "/Volumes/Samsung_T3/SKT_1/DMM_BLOCK/"
SHAPE_FILE = ['DMM_BLOCK.SHX']

data = gpd.read_file(SHAPE_DIR + SHAPE_FILE[0])

# 원하는 시, 구에 해당하는 지도 선택
def select_SI_DO_GU(data_raw, si, gu, adong = None, ldong = None):
    selected_map = data.loc[data_raw["SIDO_NM"] == si]
    selected_map = selected_map.loc[data["SGNG_NM"] == gu]
    if not adong == None:
        selected_map = selected_map.loc[data["ADONG_NM"] == adong]
    
    if not ldong == None:
        selected_map = selected_map.loc[data["LDONG_NM"] == ldong]
        
    return selected_map
    
# 특정 블락 아이디가 선택한 영역에 있는지 확인
def scan_block_ids(id_, ids_blocks):
    for id_block in ids_blocks:
        if id_block == id_:
            return True
    return False 

# 데이터에서 선택한 지도 영역에 속하는 블락 아이디만 고르기
def select_blocks(data_, ids_blocks):
    blocks = data_["BLOCK_CD"]
    in_test_set = blocks.apply(lambda id_: scan_block_ids(id_, ids_blocks))
    return data_.loc[in_test_set]

In [18]:
time_name_dict={}
for time in time_name:
    time_name_dict[time] = time.split("_")[1] + "시"

In [69]:
#
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpl

def draw_map_and_scatter(scatter_data, map_data, si, gu, adong = None, ldong = None, color_value = None, color_value_name = None):
    
    cmap = plt.cm.jet  # define the colormap
    # extract all colors from the .jet map
    cmaplist = [cmap(i) for i in range(cmap.N)]
    # force the first color entry to be grey
    cmaplist[0] = (.5, .5, .5, 1.0)
    
    # create the new map
    cmap = mpl.colors.LinearSegmentedColormap.from_list(
    'Custom cmap', cmaplist, cmap.N)
    
    #tick_wratio = np.linspace(0, 300, 11)
    tick_wratio = [1, 10, 50, 100, 500, 1000, 2000, 3000]
    print (tick_wratio)
    norm = mpl.colors.BoundaryNorm(tick_wratio, cmap.N)

    seoul_map = select_SI_DO_GU(map_data, si, gu, adong, ldong)
    total_data_seoul = select_blocks(scatter_data, seoul_map["BLOCK_CD"])
    
    fig, ax = plt.subplots()
    fig.set_size_inches(10,10)
    
    plt.subplots_adjust(bottom=0.1, right=0.3, top=0.3)

    path=ax.scatter(x = total_data_seoul["X_COORD"], y = total_data_seoul["Y_COORD"], 
                    s = total_data_seoul["total_population"]/20, label="population",
                    c = total_data_seoul[color_value], cmap=cmap, norm=norm, alpha = 0.4
                   )
    
    seoul_map.plot(ax=ax, color='white', edgecolor='black', alpha=0.5)
    
    divider = make_axes_locatable(ax)
    cax = divider.append_axes("right", size="5%", pad=0.1)
    
    # 컬러바 그리기
    cbar = plt.colorbar(path, cax=cax, ticks=tick_wratio, norm = norm, cmap=cmap, spacing='uniform', 
                        boundaries=tick_wratio )
    
    si_ = si
    gu_ = gu
    adong_ = adong
    ldong_ = ldong
    
    # 제목으로 지역정보 나타내기 (시군구동) 
    a = lambda s: '' if s is None else str(s)
    temp_title = a(si_) + " " + a(gu_) + " " + a(adong_) + " " + a(ldong_)
    fig.suptitle(temp_title, fontproperties=fontprop)
    
    # 레전드(원) 사이즈 조절
    #lgnd = plt.legend(scatterpoints=1, fontsize=10)
    #lgnd.legendHandles[0]._sizes = [20]

    #cax = fig.get_axes()[1] 
    cax.set_ylabel(time_name_dict[color_value] + " " + color_value_name, fontproperties=fontprop)

    save_fig(si+gu+"_"+color_value+color_value_name+"_visualization_plot")
    
    del fig, ax, cax, divider, seoul_map, total_data_seoul,  tick_wratio

In [ ]:
# 테스트 해보기
draw_map_and_scatter(total_data, data, "서울특별시", "종로구", None, None, "TMST_00", "일평균 유동인구 수 (명)")

In [73]:
gu_list = ["서대문구","종로구","노원구"]

In [ ]:
value_list = {time_name[0]: "일평균 유동인구 수 (명)"}

for t_name in time_name[1:]:
    value_list.update({t_name: "일평균 유동인구 수 (명)"})

for gu in gu_list:
    for key, value in value_list.items():
        draw_map_and_scatter(total_data, data, "서울특별시", gu, None, None, key, value)

In [ ]:
value_list = {time_name[0]: time_name[0]+" absolute"}

for t_name in time_name[1:]:
    value_list.update({t_name: t_name+" absolute"})

for gu in gu_list:
    for key, value in value_list.items():
        draw_map_and_scatter(total_data, data, "서울특별시", gu, None, None, key, value)

In [31]:
data.loc[data["BLOCK_CD"]=="11010550100040000008"]

,STD_YYYY,BLOCK_CD,SIDO_CD,SIDO_NM,SGNG_CD,SGNG_NM,ADONG_CD,ADONG_NM,LDONG_CD,LDONG_NM,geometry
149,2019,11010550100040000008,11,서울특별시,11110,종로구,1111055000,부암동,1111018500,홍지동,"POLYGON ((951781.3008999986 1956067.148299998,..."

In [60]:
(data.loc[data["LDONG_NM"]=="청진동"]).head()

,STD_YYYY,BLOCK_CD,SIDO_CD,SIDO_NM,SGNG_CD,SGNG_NM,ADONG_CD,ADONG_NM,LDONG_CD,LDONG_NM,geometry
348,2019,11010610300010000002,11,서울특별시,11110,종로구,1111061500,종로1.2.3.4가동,1111012200,청진동,"POLYGON ((954134.8155999999 1952585.528999999,..."
349,2019,11010610300010000003,11,서울특별시,11110,종로구,1111061500,종로1.2.3.4가동,1111012200,청진동,"POLYGON ((954091.0877999994 1952694.611300004,..."
350,2019,11010610300010000004,11,서울특별시,11110,종로구,1111061500,종로1.2.3.4가동,1111012200,청진동,"POLYGON ((954019.7755999998 1952478.8784, 9540..."
413,2019,11010610300040000013,11,서울특별시,11110,종로구,1111061500,종로1.2.3.4가동,1111012200,청진동,"POLYGON ((954284.3991999993 1952439.028100003,..."
419,2019,11010610300040000019,11,서울특별시,11110,종로구,1111061500,종로1.2.3.4가동,1111012200,청진동,"POLYGON ((954191.6783999982 1952663.9883, 9541..."